### ISSUE TITLE
windows7系统不能运行，能否补充，thank  you

### ISSUE THREAD

**Issue by vpntiger** [NiceDayk/Eudic_Windows_crack#1]

**Comment by NiceDayk** [comment]
@vpntiger  问题不详细，他人不能复现你的问题，暂不能处理。

**Comment by vpntiger** [comment]
感谢回复！你的作品能在windows11正常运行，但官网支持windows7系统的版本是之前的“老版本下载(32位, 支持Win7 Win8)
<https://www.eudic.net/download/eudic_win32.zip>”，还有许多windows7的用户

NiceDayk ***@***.***> 于2024年5月20日周一 10:50写道：
